# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: elevator-code-challenge CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  engine:
    name: Engine
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/engine
    strategy:
      matrix:
        node-version: [12.16]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Dependencies
        run: yarn
        working-directory: ${{env.working-directory}}
      - name: Test
        run: yarn test
        working-directory: ${{env.working-directory}}
